Q1

In [118]:
import pandas as pd
data = pd.read_csv('/content/daily_quotes.csv')
data.dtypes

Symbol          object
Date            object
 Close/Last    float64
 Volume          int64
 Open          float64
 High          float64
 Low           float64
dtype: object

In [119]:
data["Symbol"] = data["Symbol"].astype(str)
data["Date"] = pd.to_datetime(data["Date"])
data.dtypes

<ipython-input-119-56df123d6493>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data["Date"] = pd.to_datetime(data["Date"])

Symbol                 object
Date           datetime64[ns]
 Close/Last           float64
 Volume                 int64
 Open                 float64
 High                 float64
 Low                  float64
dtype: object

In [120]:
df = data.set_index("Symbol")
df

             Date   Close/Last     Volume      Open       High        Low
Symbol
AAPL   2021-02-12       135.37   60145130   134.350   135.5300   133.6921
AMZN   2021-02-12      3277.71    2335339  3250.000  3280.2500  3233.3100
GOOG   2021-02-12      2104.11     855865  2090.250  2108.8200  2083.1300
MSFT   2021-02-12       244.99   16561080   243.933   245.3000   242.7300
AAPL   2021-02-11       135.13   64280030   135.900   136.3900   133.7700
...           ...          ...        ...       ...        ...        ...
MSFT   2020-08-14       208.90   17958940   208.760   209.5900   207.5100
AAPL   2020-08-13       115.01  210082080   114.430   116.0425   113.9275
AMZN   2020-08-13      3161.02    3149043  3182.990  3217.5211  3155.0000
GOOG   2020-08-13      1518.45    1455208  1510.340  1537.2500  1508.0050
MSFT   2020-08-13       208.70   22588870   209.440   211.3500   208.1500

[508 rows x 6 columns]

In [127]:
data = df.iloc[:,[0,3,4,5,1,2]]
data

             Date      Open       High        Low   Close/Last     Volume
Symbol
AAPL   2021-02-12   134.350   135.5300   133.6921       135.37   60145130
AMZN   2021-02-12  3250.000  3280.2500  3233.3100      3277.71    2335339
GOOG   2021-02-12  2090.250  2108.8200  2083.1300      2104.11     855865
MSFT   2021-02-12   243.933   245.3000   242.7300       244.99   16561080
AAPL   2021-02-11   135.900   136.3900   133.7700       135.13   64280030
...           ...       ...        ...        ...          ...        ...
MSFT   2020-08-14   208.760   209.5900   207.5100       208.90   17958940
AAPL   2020-08-13   114.430   116.0425   113.9275       115.01  210082080
AMZN   2020-08-13  3182.990  3217.5211  3155.0000      3161.02    3149043
GOOG   2020-08-13  1510.340  1537.2500  1508.0050      1518.45    1455208
MSFT   2020-08-13   209.440   211.3500   208.1500       208.70   22588870

[508 rows x 6 columns]

In [128]:
df1  = data.groupby(['Symbol'])[' Volume'].max(" Volume")
df1

Symbol
AAPL    345937760
AMZN      8892580
GOOG      4330862
MSFT     69870640
Name:  Volume, dtype: int64

In [132]:
df2  = data.groupby(['Symbol']).max([df[" High"]-df[" Low"]])
df2

           Open       High       Low  Close/Last     Volume
Symbol
AAPL     143.60   145.0900   141.370      143.16  345937760
AMZN    3547.00  3552.2500  3486.685     3531.45    8892580
GOOG    2105.91  2123.5469  2083.130     2104.11    4330862
MSFT     245.00   245.9200   242.730      244.99   69870640

Q2

In [134]:
dfr = pd.read_csv('/content/textual_data.csv')
dfr.head()

,Person_1,Person_2,Person_3,Person_4,Person_5,Person_6,Person_7,Person_8,Person_9,Person_10
0,John Doe,jane smith,Tom Brown,Alice Green,CharlieBlack,Diana Prince,BRUCE WAYNE,clark kent,Peter Parker,Wade Wilson
1,john doe,JANE SMITH,tom brown,ALICE GREEN,Charlie Black,Diana prince,bruce wayne,Clark kent,Peter Parker,wade wilson
2,John Doe,Jane Smith,Tom Brown,Alice Green,Charlie Black,Diana Prince,Bruce Wayne,Clark Kent,Peter Parker,Wade Wilson
3,john doe,JANE SMITH,tom brown,ALICE GREEN,CharlieBlack,Diana Prince,BRUCE WAYNE,CLARK KENT,PETER PARKER,WADE WILSON
4,John Doe,Jane Smith,Tom Brown,Alice Green,Charlie Black,Diana Prince,Bruce Wayne,Clark Kent,Peter Parker,Wade Wilson

In [136]:
dfr.head()

,Person_1,Person_2,Person_3,Person_4,Person_5,Person_6,Person_7,Person_8,Person_9,Person_10
0,John Doe,jane smith,Tom Brown,Alice Green,CharlieBlack,Diana Prince,BRUCE WAYNE,clark kent,Peter Parker,Wade Wilson
1,john doe,JANE SMITH,tom brown,ALICE GREEN,Charlie Black,Diana prince,bruce wayne,Clark kent,Peter Parker,wade wilson
2,John Doe,Jane Smith,Tom Brown,Alice Green,Charlie Black,Diana Prince,Bruce Wayne,Clark Kent,Peter Parker,Wade Wilson
3,john doe,JANE SMITH,tom brown,ALICE GREEN,CharlieBlack,Diana Prince,BRUCE WAYNE,CLARK KENT,PETER PARKER,WADE WILSON
4,John Doe,Jane Smith,Tom Brown,Alice Green,Charlie Black,Diana Prince,Bruce Wayne,Clark Kent,Peter Parker,Wade Wilson

In [138]:
melted_df = dfr.melt(var_name='Person_ID', value_name='Name')
melted_df

    Person_ID            Name
0    Person_1       John Doe
1    Person_1       john doe
2    Person_1      John  Doe
3    Person_1        john doe
4    Person_1     John   Doe
..        ...             ...
95  Person_10     wade wilson
96  Person_10    Hope VanDyne
97  Person_10    HOPE VANDYNE
98  Person_10    hope vandyne
99  Person_10   Hope VanDyne

[100 rows x 2 columns]

In [139]:
dfr.head()

,Person_1,Person_2,Person_3,Person_4,Person_5,Person_6,Person_7,Person_8,Person_9,Person_10
0,John Doe,jane smith,Tom Brown,Alice Green,CharlieBlack,Diana Prince,BRUCE WAYNE,clark kent,Peter Parker,Wade Wilson
1,john doe,JANE SMITH,tom brown,ALICE GREEN,Charlie Black,Diana prince,bruce wayne,Clark kent,Peter Parker,wade wilson
2,John Doe,Jane Smith,Tom Brown,Alice Green,Charlie Black,Diana Prince,Bruce Wayne,Clark Kent,Peter Parker,Wade Wilson
3,john doe,JANE SMITH,tom brown,ALICE GREEN,CharlieBlack,Diana Prince,BRUCE WAYNE,CLARK KENT,PETER PARKER,WADE WILSON
4,John Doe,Jane Smith,Tom Brown,Alice Green,Charlie Black,Diana Prince,Bruce Wayne,Clark Kent,Peter Parker,Wade Wilson

In [147]:
#3
melted_df['Name'] = melted_df['Name'].str.title()
melted_df[['First_Name', 'Last_Name']] = melted_df['Name'].str.split(' ',n=1, expand=True)
melted_df = melted_df.drop(columns=['Name'])
melted_df

    Person_ID First_Name      Last_Name
0    Person_1                 John Doe
1    Person_1       John           Doe
2    Person_1       John           Doe
3    Person_1       John            Doe
4    Person_1       John           Doe
..        ...        ...            ...
95  Person_10       Wade         Wilson
96  Person_10       Hope        Vandyne
97  Person_10       Hope        Vandyne
98  Person_10       Hope        Vandyne
99  Person_10             Hope Vandyne

[100 rows x 3 columns]

In [150]:
#4
#Sort the DataFrame by Last_Name in alphabetical order and display the
df_sorted = melted_df.sort_values(by='Last_Name', ascending=True)
df_sorted

    Person_ID    First_Name  Last_Name
80   Person_9         Peter     Parker
22   Person_3           Tom      Brown
4    Person_1          John       Doe
30   Person_4         Alice      Green
68   Person_7          Thor    Odinson
..        ...           ...        ...
94  Person_10          Wade     Wilson
95  Person_10          Wade     Wilson
90  Person_10          Wade     Wilson
40   Person_5  Charlieblack       None
43   Person_5  Charlieblack       None

[100 rows x 3 columns]

In [153]:
#5
df_sorted['First_Name_Length'] = df_sorted['First_Name'].str.len()

In [154]:
#6
df_filtered = df_sorted[df_sorted['Last_Name'].str.startswith('S',na=False)]

In [155]:
#7
df_grouped = melted_df.groupby('Last_Name').size().reset_index(name='Count')

In [160]:
#8
file_path = '/content/textual_data.csv'
melted_df.to_csv(file_path, index=False)