In [ ]:
import pandas as pd
from io import StringIO

# Updated dataset
data = """EmployeeID,Name,Department,Salary,HireDate
101,Alice Smith,IT,70000,2018-03-20
102,Bob Johnson,HR,50000,2020-05-10
103,Charlie King,IT,72000,2017-09-12
104,David Brown,Finance,80000,2015-06-01
105,Eva Green,IT,68000,2019-11-11
106,Frank White,HR,53000,2020-07-15
107,Gina Black,Marketing,62000,2019-01-30
108,Hannah Blue,Finance,78000,2016-08-09
109,Ian Gray,IT,69000,2018-12-14
110,Jack Gold,Marketing,59000,2021-01-02
111,Jane Silver,HR,54000,2017-10-05
112,Karl White,IT,71000,2019-02-25
113,Liam Green,Finance,82000,2014-11-15
114,Mary Brown,Marketing,60000,2020-04-23
115,Nancy Black,IT,67000,2019-09-10
116,Oscar White,HR,55000,2018-01-15
117,Paul King,Finance,79000,2015-03-30
118,Quinn Gray,IT,75000,2021-02-19
119,Rachel Green,Marketing,61000,2018-08-08
120,Steve Brown,Finance,83000,2014-09-12
101,Alice Smith,IT,70000,2018-03-20
102,Bob Johnson,HR,50000,2020-05-10
121,Tim Gold,HR,56000,2021-01-01
122,Uma Silver,IT,74000,2020-07-14
123,Vince Blue,Marketing,63000,2017-06-30
124,Wendy Black,Finance,85000,2013-10-18
125,Xavier Green,IT,66000,2021-04-20
126,Yara White,HR,58000,2019-11-07
127,Zack Brown,Marketing,64000,2017-03-13
128,Andy Black,IT,67000,2018-06-21
129,Bella Gray,Finance,86000,2015-08-10
130,Chris White,HR,57000,2016-11-23
131,Diana King,IT,69000,2021-06-14
132,Emily Brown,Marketing,66000,2020-09-29
133,Finn Green,IT,75000,2018-02-11
134,George Black,HR,60000,2017-07-05
135,Helen Gold,Finance,87000,2014-04-19
136,Isaac Gray,Marketing,67000,2016-09-21
137,Jack White,IT,78000,2015-12-12
138,Kevin Green,Finance,86000,2014-03-08
139,Lucy Brown,HR,61000,2021-05-16
140,Mike Black,Marketing,65000,2017-10-07
104,David Brown,Finance,80000,2015-06-01
111,Jane Silver,HR,54000,2017-10-05
"""

# Create DataFrame
df = pd.read_csv(StringIO(data))

# Save the DataFrame to a CSV file
df.to_csv("employee_data.csv", index=False)

print("CSV file has been created successfully!")

CSV file has been created successfully!

##**Basic Functions**

1. Loading and Inspecting Data\
   pd.read_csv(): Reads a CSV file into a DataFrame.

In [ ]:
df = pd.read_csv('employee_data.csv')

2. df.head(): Displays the first 5 rows of the DataFrame.

In [ ]:
df.head()

   EmployeeID          Name Department  Salary    HireDate
0         101   Alice Smith         IT   70000  2018-03-20
1         102   Bob Johnson         HR   50000  2020-05-10
2         103  Charlie King         IT   72000  2017-09-12
3         104   David Brown    Finance   80000  2015-06-01
4         105     Eva Green         IT   68000  2019-11-11

df.tail(): Displays the last 5 rows of the DataFrame.

In [ ]:
df.tail()

    EmployeeID         Name Department  Salary    HireDate
39         138  Kevin Green    Finance   86000  2014-03-08
40         139   Lucy Brown         HR   61000  2021-05-16
41         140   Mike Black  Marketing   65000  2017-10-07
42         104  David Brown    Finance   80000  2015-06-01
43         111  Jane Silver         HR   54000  2017-10-05

#### 4) df.shape: Returns the dimensions of the DataFrame (rows, columns).

In [ ]:
df.shape

(44, 5)

####5) df.info(): Provides a summary of the DataFrame, including data types and missing values.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  44 non-null     int64
 1   Name        44 non-null     object
 2   Department  44 non-null     object
 3   Salary      44 non-null     int64
 4   HireDate    44 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.8+ KB

####6) df.describe(): Generates descriptive statistics for numerical columns.

In [ ]:
df.describe()

       EmployeeID        Salary
count   44.000000     44.000000
mean   119.045455  68000.000000
std     12.125227  10454.775253
min    101.000000  50000.000000
25%    108.750000  60000.000000
50%    118.500000  67000.000000
75%    129.250000  75750.000000
max    140.000000  87000.000000

##**2. Selecting and Filtering Data**

df['column_name']: Access a single column by name.

1.   List item
2.   List item

In [ ]:
df['Name']

0      Alice Smith
1      Bob Johnson
2     Charlie King
3      David Brown
4        Eva Green
5      Frank White
6       Gina Black
7      Hannah Blue
8         Ian Gray
9        Jack Gold
10     Jane Silver
11      Karl White
12      Liam Green
13      Mary Brown
14     Nancy Black
15     Oscar White
16       Paul King
17      Quinn Gray
18    Rachel Green
19     Steve Brown
20     Alice Smith
21     Bob Johnson
22        Tim Gold
23      Uma Silver
24      Vince Blue
25     Wendy Black
26    Xavier Green
27      Yara White
28      Zack Brown
29      Andy Black
30      Bella Gray
31     Chris White
32      Diana King
33     Emily Brown
34      Finn Green
35    George Black
36      Helen Gold
37      Isaac Gray
38      Jack White
39     Kevin Green
40      Lucy Brown
41      Mike Black
42     David Brown
43     Jane Silver
Name: Name, dtype: object

* df[['col1', 'col2']]: Select multiple columns.

In [ ]:
df[['Name', 'Department']]

            Name Department
0    Alice Smith         IT
1    Bob Johnson         HR
2   Charlie King         IT
3    David Brown    Finance
4      Eva Green         IT
5    Frank White         HR
6     Gina Black  Marketing
7    Hannah Blue    Finance
8       Ian Gray         IT
9      Jack Gold  Marketing
10   Jane Silver         HR
11    Karl White         IT
12    Liam Green    Finance
13    Mary Brown  Marketing
14   Nancy Black         IT
15   Oscar White         HR
16     Paul King    Finance
17    Quinn Gray         IT
18  Rachel Green  Marketing
19   Steve Brown    Finance
20   Alice Smith         IT
21   Bob Johnson         HR
22      Tim Gold         HR
23    Uma Silver         IT
24    Vince Blue  Marketing
25   Wendy Black    Finance
26  Xavier Green         IT
27    Yara White         HR
28    Zack Brown  Marketing
29    Andy Black         IT
30    Bella Gray    Finance
31   Chris White         HR
32    Diana King         IT
33   Emily Brown  Marketing
34    Finn Green         IT
35  George Black         HR
36    Helen Gold    Finance
37    Isaac Gray  Marketing
38    Jack White         IT
39   Kevin Green    Finance
40    Lucy Brown         HR
41    Mike Black  Marketing
42   David Brown    Finance
43   Jane Silver         HR

* df.iloc[] and df.loc[]: Select rows by index (iloc[]) or by label/index (loc[]).

In [ ]:
# Select first 5 rows using iloc
df.iloc[:5]

# Select rows where EmployeeID is 102 using loc
df.loc[df['EmployeeID'] == 103]

   EmployeeID          Name Department  Salary    HireDate
2         103  Charlie King         IT   72000  2017-09-12

* Conditional Filtering: Select rows based on conditions.

In [ ]:
# Employees in IT department
df[df['Department'] == 'IT']

# Employees with salary > 60000
df[df['Salary'] > 60000]

    EmployeeID          Name Department  Salary    HireDate
0          101   Alice Smith         IT   70000  2018-03-20
2          103  Charlie King         IT   72000  2017-09-12
3          104   David Brown    Finance   80000  2015-06-01
4          105     Eva Green         IT   68000  2019-11-11
6          107    Gina Black  Marketing   62000  2019-01-30
7          108   Hannah Blue    Finance   78000  2016-08-09
8          109      Ian Gray         IT   69000  2018-12-14
11         112    Karl White         IT   71000  2019-02-25
12         113    Liam Green    Finance   82000  2014-11-15
14         115   Nancy Black         IT   67000  2019-09-10
16         117     Paul King    Finance   79000  2015-03-30
17         118    Quinn Gray         IT   75000  2021-02-19
18         119  Rachel Green  Marketing   61000  2018-08-08
19         120   Steve Brown    Finance   83000  2014-09-12
20         101   Alice Smith         IT   70000  2018-03-20
23         122    Uma Silver         IT   74000  2020-07-14
24         123    Vince Blue  Marketing   63000  2017-06-30
25         124   Wendy Black    Finance   85000  2013-10-18
26         125  Xavier Green         IT   66000  2021-04-20
28         127    Zack Brown  Marketing   64000  2017-03-13
29         128    Andy Black         IT   67000  2018-06-21
30         129    Bella Gray    Finance   86000  2015-08-10
32         131    Diana King         IT   69000  2021-06-14
33         132   Emily Brown  Marketing   66000  2020-09-29
34         133    Finn Green         IT   75000  2018-02-11
36         135    Helen Gold    Finance   87000  2014-04-19
37         136    Isaac Gray  Marketing   67000  2016-09-21
38         137    Jack White         IT   78000  2015-12-12
39         138   Kevin Green    Finance   86000  2014-03-08
40         139    Lucy Brown         HR   61000  2021-05-16
41         140    Mike Black  Marketing   65000  2017-10-07
42         104   David Brown    Finance   80000  2015-06-01

##**3. Modifying Data**

* df['NewColumn'] = ...: Create a new column.

In [ ]:
# Adding a new column 'Bonus' which is 10% of Salary
df['Bonus'] = df['Salary'] * 0.10

* remove duplicates using the drop_duplicates() function.

In [ ]:
# Removing duplicates
df_no_duplicates = df.drop_duplicates()
print(f"Original shape: {df.shape}")
print(f"Shape after removing duplicates: {df_no_duplicates.shape}")

Original shape: (44, 6)
Shape after removing duplicates: (40, 6)

In [ ]:
 df.drop_duplicates()

    EmployeeID          Name Department  Salary    HireDate   Bonus
0          101   Alice Smith         IT   70000  2018-03-20  7000.0
1          102   Bob Johnson         HR   50000  2020-05-10  5000.0
2          103  Charlie King         IT   72000  2017-09-12  7200.0
3          104   David Brown    Finance   80000  2015-06-01  8000.0
4          105     Eva Green         IT   68000  2019-11-11  6800.0
5          106   Frank White         HR   53000  2020-07-15  5300.0
6          107    Gina Black  Marketing   62000  2019-01-30  6200.0
7          108   Hannah Blue    Finance   78000  2016-08-09  7800.0
8          109      Ian Gray         IT   69000  2018-12-14  6900.0
9          110     Jack Gold  Marketing   59000  2021-01-02  5900.0
10         111   Jane Silver         HR   54000  2017-10-05  5400.0
11         112    Karl White         IT   71000  2019-02-25  7100.0
12         113    Liam Green    Finance   82000  2014-11-15  8200.0
13         114    Mary Brown  Marketing   60000  2020-04-23  6000.0
14         115   Nancy Black         IT   67000  2019-09-10  6700.0
15         116   Oscar White         HR   55000  2018-01-15  5500.0
16         117     Paul King    Finance   79000  2015-03-30  7900.0
17         118    Quinn Gray         IT   75000  2021-02-19  7500.0
18         119  Rachel Green  Marketing   61000  2018-08-08  6100.0
19         120   Steve Brown    Finance   83000  2014-09-12  8300.0
22         121      Tim Gold         HR   56000  2021-01-01  5600.0
23         122    Uma Silver         IT   74000  2020-07-14  7400.0
24         123    Vince Blue  Marketing   63000  2017-06-30  6300.0
25         124   Wendy Black    Finance   85000  2013-10-18  8500.0
26         125  Xavier Green         IT   66000  2021-04-20  6600.0
27         126    Yara White         HR   58000  2019-11-07  5800.0
28         127    Zack Brown  Marketing   64000  2017-03-13  6400.0
29         128    Andy Black         IT   67000  2018-06-21  6700.0
30         129    Bella Gray    Finance   86000  2015-08-10  8600.0
31         130   Chris White         HR   57000  2016-11-23  5700.0
32         131    Diana King         IT   69000  2021-06-14  6900.0
33         132   Emily Brown  Marketing   66000  2020-09-29  6600.0
34         133    Finn Green         IT   75000  2018-02-11  7500.0
35         134  George Black         HR   60000  2017-07-05  6000.0
36         135    Helen Gold    Finance   87000  2014-04-19  8700.0
37         136    Isaac Gray  Marketing   67000  2016-09-21  6700.0
38         137    Jack White         IT   78000  2015-12-12  7800.0
39         138   Kevin Green    Finance   86000  2014-03-08  8600.0
40         139    Lucy Brown         HR   61000  2021-05-16  6100.0
41         140    Mike Black  Marketing   65000  2017-10-07  6500.0

* df.drop(): Drop columns or rows.

In [ ]:
# Dropping the 'Bonus' column
df.drop('Bonus', axis=1, inplace=True)

* df.sort_values(): Sort data by column values.

In [ ]:
df.sort_values('Salary', ascending=False)

    EmployeeID          Name Department  Salary    HireDate
36         135    Helen Gold    Finance   87000  2014-04-19
30         129    Bella Gray    Finance   86000  2015-08-10
39         138   Kevin Green    Finance   86000  2014-03-08
25         124   Wendy Black    Finance   85000  2013-10-18
19         120   Steve Brown    Finance   83000  2014-09-12
12         113    Liam Green    Finance   82000  2014-11-15
42         104   David Brown    Finance   80000  2015-06-01
3          104   David Brown    Finance   80000  2015-06-01
16         117     Paul King    Finance   79000  2015-03-30
7          108   Hannah Blue    Finance   78000  2016-08-09
38         137    Jack White         IT   78000  2015-12-12
34         133    Finn Green         IT   75000  2018-02-11
17         118    Quinn Gray         IT   75000  2021-02-19
23         122    Uma Silver         IT   74000  2020-07-14
2          103  Charlie King         IT   72000  2017-09-12
11         112    Karl White         IT   71000  2019-02-25
20         101   Alice Smith         IT   70000  2018-03-20
0          101   Alice Smith         IT   70000  2018-03-20
8          109      Ian Gray         IT   69000  2018-12-14
32         131    Diana King         IT   69000  2021-06-14
4          105     Eva Green         IT   68000  2019-11-11
37         136    Isaac Gray  Marketing   67000  2016-09-21
14         115   Nancy Black         IT   67000  2019-09-10
29         128    Andy Black         IT   67000  2018-06-21
33         132   Emily Brown  Marketing   66000  2020-09-29
26         125  Xavier Green         IT   66000  2021-04-20
41         140    Mike Black  Marketing   65000  2017-10-07
28         127    Zack Brown  Marketing   64000  2017-03-13
24         123    Vince Blue  Marketing   63000  2017-06-30
6          107    Gina Black  Marketing   62000  2019-01-30
18         119  Rachel Green  Marketing   61000  2018-08-08
40         139    Lucy Brown         HR   61000  2021-05-16
13         114    Mary Brown  Marketing   60000  2020-04-23
35         134  George Black         HR   60000  2017-07-05
9          110     Jack Gold  Marketing   59000  2021-01-02
27         126    Yara White         HR   58000  2019-11-07
31         130   Chris White         HR   57000  2016-11-23
22         121      Tim Gold         HR   56000  2021-01-01
15         116   Oscar White         HR   55000  2018-01-15
10         111   Jane Silver         HR   54000  2017-10-05
43         111   Jane Silver         HR   54000  2017-10-05
5          106   Frank White         HR   53000  2020-07-15
1          102   Bob Johnson         HR   50000  2020-05-10
21         102   Bob Johnson         HR   50000  2020-05-10

##**4) Handling Missing Data**

* df.isnull(): Check for missing values.

In [ ]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Salary        0
HireDate      0
dtype: int64

* df.fillna(): Fill missing values with a specified value.

In [ ]:
# Fill missing Salary values with 0
df['Salary'].fillna(0, inplace=True)

<ipython-input-19-4dc192f3eddd>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(0, inplace=True)

* df.dropna(): Drop rows or columns with missing data.

In [ ]:
# Drop rows where any value is NaN
df.dropna(inplace=True)

##**5) Aggregation and Grouping**

* df.groupby(): Group data by column(s) and apply aggregation.

In [ ]:
# Group by Department and get average Salary
df.groupby('Department')['Salary'].mean()

Department
Finance      82600.000000
HR           55272.727273
IT           70785.714286
Marketing    63000.000000
Name: Salary, dtype: float64

* df.agg(): Perform multiple aggregations.

In [ ]:
# Perform multiple aggregations on Salary
df.agg({'Salary': ['mean', 'max', 'min']})

       Salary
mean  68000.0
max   87000.0
min   50000.0

##**6) Advanced functions**

#### Merging and Joining DataFrames


*   pd.merge(): Merge two DataFrames based on a common column.

In [ ]:
# Suppose we have another DataFrame 'dept_info'
dept_info = pd.DataFrame({
    'Department': ['IT', 'HR', 'Finance', 'Marketing'],
    'Manager': ['John Doe', 'Jane Smith', 'Mike Green', 'Nina Jones']
})

# Merge the two DataFrames
merged_df = pd.merge(df, dept_info, on='Department')
merged_df

    EmployeeID          Name Department  Salary    HireDate     Manager
0          101   Alice Smith         IT   70000  2018-03-20    John Doe
1          102   Bob Johnson         HR   50000  2020-05-10  Jane Smith
2          103  Charlie King         IT   72000  2017-09-12    John Doe
3          104   David Brown    Finance   80000  2015-06-01  Mike Green
4          105     Eva Green         IT   68000  2019-11-11    John Doe
5          106   Frank White         HR   53000  2020-07-15  Jane Smith
6          107    Gina Black  Marketing   62000  2019-01-30  Nina Jones
7          108   Hannah Blue    Finance   78000  2016-08-09  Mike Green
8          109      Ian Gray         IT   69000  2018-12-14    John Doe
9          110     Jack Gold  Marketing   59000  2021-01-02  Nina Jones
10         111   Jane Silver         HR   54000  2017-10-05  Jane Smith
11         112    Karl White         IT   71000  2019-02-25    John Doe
12         113    Liam Green    Finance   82000  2014-11-15  Mike Green
13         114    Mary Brown  Marketing   60000  2020-04-23  Nina Jones
14         115   Nancy Black         IT   67000  2019-09-10    John Doe
15         116   Oscar White         HR   55000  2018-01-15  Jane Smith
16         117     Paul King    Finance   79000  2015-03-30  Mike Green
17         118    Quinn Gray         IT   75000  2021-02-19    John Doe
18         119  Rachel Green  Marketing   61000  2018-08-08  Nina Jones
19         120   Steve Brown    Finance   83000  2014-09-12  Mike Green
20         101   Alice Smith         IT   70000  2018-03-20    John Doe
21         102   Bob Johnson         HR   50000  2020-05-10  Jane Smith
22         121      Tim Gold         HR   56000  2021-01-01  Jane Smith
23         122    Uma Silver         IT   74000  2020-07-14    John Doe
24         123    Vince Blue  Marketing   63000  2017-06-30  Nina Jones
25         124   Wendy Black    Finance   85000  2013-10-18  Mike Green
26         125  Xavier Green         IT   66000  2021-04-20    John Doe
27         126    Yara White         HR   58000  2019-11-07  Jane Smith
28         127    Zack Brown  Marketing   64000  2017-03-13  Nina Jones
29         128    Andy Black         IT   67000  2018-06-21    John Doe
30         129    Bella Gray    Finance   86000  2015-08-10  Mike Green
31         130   Chris White         HR   57000  2016-11-23  Jane Smith
32         131    Diana King         IT   69000  2021-06-14    John Doe
33         132   Emily Brown  Marketing   66000  2020-09-29  Nina Jones
34         133    Finn Green         IT   75000  2018-02-11    John Doe
35         134  George Black         HR   60000  2017-07-05  Jane Smith
36         135    Helen Gold    Finance   87000  2014-04-19  Mike Green
37         136    Isaac Gray  Marketing   67000  2016-09-21  Nina Jones
38         137    Jack White         IT   78000  2015-12-12    John Doe
39         138   Kevin Green    Finance   86000  2014-03-08  Mike Green
40         139    Lucy Brown         HR   61000  2021-05-16  Jane Smith
41         140    Mike Black  Marketing   65000  2017-10-07  Nina Jones
42         104   David Brown    Finance   80000  2015-06-01  Mike Green
43         111   Jane Silver         HR   54000  2017-10-05  Jane Smith

Pivot Tables

*   df.pivot_table(): Create a pivot table to summarize data.

In [ ]:
# Create a pivot table showing the average Salary per Department
df.pivot_table(values='Salary', index='Department', aggfunc='mean')

                  Salary
Department
Finance     82600.000000
HR          55272.727273
IT          70785.714286
Marketing   63000.000000

##**9. Reshaping Data**
* df.melt(): Convert a DataFrame from wide to long format.

In [ ]:
# Reshape data to have Department and Salary as individual rows
melted_df = df.melt(id_vars=['Name'], value_vars=['Department', 'Salary'])
melted_df

            Name    variable    value
0    Alice Smith  Department       IT
1    Bob Johnson  Department       HR
2   Charlie King  Department       IT
3    David Brown  Department  Finance
4      Eva Green  Department       IT
..           ...         ...      ...
83   Kevin Green      Salary    86000
84    Lucy Brown      Salary    61000
85    Mike Black      Salary    65000
86   David Brown      Salary    80000
87   Jane Silver      Salary    54000

[88 rows x 3 columns]



*   df.pivot(): Pivot the DataFrame based on column values.

In [ ]:
# Pivot the data with EmployeeID as columns and values as Salary
pivoted_df = df.pivot(index='EmployeeID', columns='Name', values='Salary')

ValueError: Index contains duplicate entries, cannot reshape

###**10. Time Series Handling**
* pd.to_datetime(): Convert a column to DateTime.

In [ ]:
# Convert HireDate to DateTime
df['HireDate'] = pd.to_datetime(df['HireDate'])
df

    EmployeeID          Name Department  Salary   HireDate
0          101   Alice Smith         IT   70000 2018-03-20
1          102   Bob Johnson         HR   50000 2020-05-10
2          103  Charlie King         IT   72000 2017-09-12
3          104   David Brown    Finance   80000 2015-06-01
4          105     Eva Green         IT   68000 2019-11-11
5          106   Frank White         HR   53000 2020-07-15
6          107    Gina Black  Marketing   62000 2019-01-30
7          108   Hannah Blue    Finance   78000 2016-08-09
8          109      Ian Gray         IT   69000 2018-12-14
9          110     Jack Gold  Marketing   59000 2021-01-02
10         111   Jane Silver         HR   54000 2017-10-05
11         112    Karl White         IT   71000 2019-02-25
12         113    Liam Green    Finance   82000 2014-11-15
13         114    Mary Brown  Marketing   60000 2020-04-23
14         115   Nancy Black         IT   67000 2019-09-10
15         116   Oscar White         HR   55000 2018-01-15
16         117     Paul King    Finance   79000 2015-03-30
17         118    Quinn Gray         IT   75000 2021-02-19
18         119  Rachel Green  Marketing   61000 2018-08-08
19         120   Steve Brown    Finance   83000 2014-09-12
20         101   Alice Smith         IT   70000 2018-03-20
21         102   Bob Johnson         HR   50000 2020-05-10
22         121      Tim Gold         HR   56000 2021-01-01
23         122    Uma Silver         IT   74000 2020-07-14
24         123    Vince Blue  Marketing   63000 2017-06-30
25         124   Wendy Black    Finance   85000 2013-10-18
26         125  Xavier Green         IT   66000 2021-04-20
27         126    Yara White         HR   58000 2019-11-07
28         127    Zack Brown  Marketing   64000 2017-03-13
29         128    Andy Black         IT   67000 2018-06-21
30         129    Bella Gray    Finance   86000 2015-08-10
31         130   Chris White         HR   57000 2016-11-23
32         131    Diana King         IT   69000 2021-06-14
33         132   Emily Brown  Marketing   66000 2020-09-29
34         133    Finn Green         IT   75000 2018-02-11
35         134  George Black         HR   60000 2017-07-05
36         135    Helen Gold    Finance   87000 2014-04-19
37         136    Isaac Gray  Marketing   67000 2016-09-21
38         137    Jack White         IT   78000 2015-12-12
39         138   Kevin Green    Finance   86000 2014-03-08
40         139    Lucy Brown         HR   61000 2021-05-16
41         140    Mike Black  Marketing   65000 2017-10-07
42         104   David Brown    Finance   80000 2015-06-01
43         111   Jane Silver         HR   54000 2017-10-05

*   df.resample(): Resample time series data to different frequencies.

In [ ]:
# Resample by year and get average Salary
df.set_index('HireDate').resample('Y')['Salary'].mean()

<ipython-input-28-1868b6aac46a>:2: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  df.set_index('HireDate').resample('Y')['Salary'].mean()

HireDate
2013-12-31    85000.000000
2014-12-31    84500.000000
2015-12-31    80600.000000
2016-12-31    67333.333333
2017-12-31    61714.285714
2018-12-31    66714.285714
2019-12-31    65200.000000
2020-12-31    58833.333333
2021-12-31    64333.333333
Freq: YE-DEC, Name: Salary, dtype: float64


##Assignment

$\textbf{Data Reference}$

To access the dataset required for these coding questions,please visit the \\ following link:

$\texttt{https://gist.github.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6} $

$\textbf{Coding Questions}$


1. Use $ \texttt{iloc} $ to read and display the first 5 rows of the second column in the frame.
2. Access and print the element located in the third row and the second column of the DataFrame.
3. Filter the DataFrame to return all instances where $\texttt{Type 1}$ is "Fire".
4. Generate a descriptive statistics summary of the DataFrame using the $\texttt{describe()}$ method.
5. Check if there are any null values in the DataFrame.
6. Calculate and display the total number of null values in the DataFrame.
7. Create a copy of the DataFrame and replace NaN values in the $\texttt{Type 2}$ column with the string 'Unknown'.
8. Remove any columns in the DataFrame that contain missing values.
9. Sort the DataFrame by the $\texttt{Name}$ column in descending order.
10. Add a new column named $\texttt{Total}$ to the DataFrame that sums the values of the $\texttt{HP}$, $\texttt{Attack}$, $\texttt{Sp. Atk}$, $\texttt{Sp. Def}$, and $\texttt{Speed}$ columns.
11. Drop the column named $\texttt{Total}$ from the DataFrame.
Save the modified DataFrame to a CSV file named $\texttt{modified.csv}$.
12. Filter the DataFrame to return instances where $\texttt{Type 1}$ is "Grass" and $\texttt{Type 2}$ is "Poison".
13. Return all instances where $\texttt{Type 1}$ is "Grass" or $\texttt{Type 2}$ is "Poison".
14. Use a combination of conditions to filter the DataFrame for instances where $\texttt{Type 1}$ is "Grass" and $\texttt{Type 2}$ is "Poison" or $\texttt{HP}$ is equal to 45.
15. Create a new DataFrame that returns instances where $\texttt{Type 1}$ is "Grass", $\texttt{Type 2}$ is "Poison", and $\texttt{HP}$ is greater than 70.
Reset the index of the new DataFrame after filtering.
16. Search for instances where the $\texttt{Name}$ column contains the substring 'Mega'.
17. Replace all instances of $\texttt{Type 1}$ being "Fire" with "Flame".
18. Add a new column $\texttt{Total}$ that sums the values of $\texttt{HP}$, $\texttt{Attack}$, $\texttt{Sp. Atk}$, $\texttt{Sp. Def}$, and $\texttt{Speed}$ again.
19. Replace values in the $\texttt{Generation}$ and $\texttt{Legendary}$ columns with 'Test 1' and 'Test 2' for rows where the $\texttt{Total}$ is greater than 500.
20. Group the DataFrame by $\texttt{Type 1}$ and calculate the mean for each group across all columns.
21. Group the DataFrame by $\texttt{Type 1}$ and calculate the sum of the $\texttt{Attack}$ column.
22. Group the DataFrame by both $\texttt{Type 1}$ and $\texttt{Type 2}$ and calculate the sum of the $\texttt{Attack}$ column.